[app]
name      = "ClickHouseApp"
bundle_id = "com.breakfastlabs.clickhouse"
version   = "0.1.0"

[build]
icon.src        = "Sources/ClickHouseApp/Resources/clickhouse.svg"
icon.scale      = 0.9  # optional
icon.background = "#FCFF74"
